- name: Build Android release APK when create new tag
  # You may pin to the exact commit or the version.
  # uses: kyze8439690/action-release-releaseapk@87b79766279011a72b441e3da6cb5b806f5a534e
  uses: kyze8439690/action-release-releaseapk@1.0.0
  with:
    # Github secret token to allow automated publishing of APK to release.
    GITHUB_TOKEN: # optional
